# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: 'ubuntu-latest'
  
# Does not work without this:
variables:
  secrectVar: ${ replace(  $[variables['secrectVar']], 'variables['secrectVar']', '' ) }

steps:
- pwsh: |      
    echo secrectVar_Macro         $env:secrectVar_Macro
    echo secrectVar_CompileTime   $env:secrectVar_CompileTime
    echo secrectVar_Runtime       $env:secrectVar_Runtime

  env:
    secrectVar_Macro: $(secrectVar)
    secrectVar_CompileTime: ${{variables.secrectVar}}
    secrectVar_Runtime: $[ variables['secrectVar'] ]